version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    # environment:
    #   - REACT_APP_API_URL=http://backend:8080  
    environment:
      - http://localhost:8080  
    volumes:
      - ./frontend:/app  
      - /app/node_modules  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app  --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge