# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     networks:
#       - app-network
#     #environment:
#      #    - REACT_APP_API_URL=http://localhost:8080  
#     environment:
#       -  http://localhost:8080  
#     volumes:
#       - ./frontend:/app  
#       - /app/node_modules  

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     command: uvicorn --host 0.0.0.0 main:app  --port 8080 --reload
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./backend:/app
#     environment:
#       - CORS_ORIGIN=http://localhost:3000
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  redis_data: